/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rtsistema.views;

import br.com.rtisistemas.tableModel.ClientesTableModel;
import br.com.rtsistema.domain.Cliente;

import br.com.rtsistema.domain.ComboModelTamanho;
import br.com.rtsistema.domain.Telefone;

import br.com.rtsistema.persistence.CadastroChamadosDao;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Helton
 */
public class CadastroChamados extends javax.swing.JDialog {

    Clientes cliente = new Clientes();
    ClientesTableModel clTableModel = new ClientesTableModel();
    private List<Cliente> clientes;

    public CadastroChamados(Cliente cliente) {
        initComponents();
        initValues();
        jTCpfCnpj.setText(cliente.getCpf());
        jTNomeCliente.setText(cliente.getNome());
        jTNomeFantasia.setText(cliente.getFantasia());
        Telefone telefone = cliente.getTelefone();
        jTContato.setText(telefone.getTelefone1());
        setModal(true);
    }

    public CadastroChamados() {
        initComponents();
        initValues();
        
    }
    

    private void initValues() {
        Date hoje = new Date();
        String dtFormatado = new SimpleDateFormat("DD/mm/yyyy").format(hoje);
        jFData.setText(dtFormatado);
        ComboModelTamanho cbModelTamanho = new ComboModelTamanho();
        jCClassificacao.setModel(cbModelTamanho);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jBBuscarCliente = new javax.swing.JButton();
        jLNomeCliente = new javax.swing.JLabel();
        jTNomeCliente = new javax.swing.JTextField();
        jLCpfCnpj = new javax.swing.JLabel();
        jTCpfCnpj = new javax.swing.JTextField();
        jLNomeFantasia = new javax.swing.JLabel();
        jTNomeFantasia = new javax.swing.JTextField();
        jLContato = new javax.swing.JLabel();
        jTContato = new javax.swing.JTextField();
        jLReclamante = new javax.swing.JLabel();
        jTReclamante = new javax.swing.JTextField();
        jLNumChamado = new javax.swing.JLabel();
        jTNumChamado = new javax.swing.JTextField();
        jLClassificacao = new javax.swing.JLabel();
        jCClassificacao = new javax.swing.JComboBox<>();
        jLData = new javax.swing.JLabel();
        jFData = new javax.swing.JFormattedTextField();
        jLAtendende = new javax.swing.JLabel();
        jTAtendente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLProblemaRelatado = new javax.swing.JLabel();
        jSProblemaRelatado = new javax.swing.JScrollPane();
        jTProblemaRelatado = new javax.swing.JTextPane();
        jLDadosAnalisados = new javax.swing.JLabel();
        jSDadosAnalisados = new javax.swing.JScrollPane();
        jTDadosAnalisados = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLPossivelSolucao = new javax.swing.JLabel();
        jSPossivelSolucao = new javax.swing.JScrollPane();
        jTPossivelSolucao = new javax.swing.JTextPane();
        jLSolucaoAplicada = new javax.swing.JLabel();
        jSsolucaoAplicada = new javax.swing.JScrollPane();
        jTSolucaoAplicada = new javax.swing.JTextArea();
        jBCancelar = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/businessman_view.png"))); // NOI18N
        jBBuscarCliente.setText("Buscar Cliente");
        jBBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarClienteActionPerformed(evt);
            }
        });

        jLNomeCliente.setText("Nome do Cliente:");

        jLCpfCnpj.setText("CPF / CNPJ:");

        jLNomeFantasia.setText("Nome Fantasia:");

        jLContato.setText("Contato:");

        jLReclamante.setText("Reclamante:");

        jLNumChamado.setText("Numero do Chamado:");

        jLClassificacao.setText("Classificação:");

        jCClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCClassificacaoActionPerformed(evt);
            }
        });

        jLData.setText("Data:");

        jLAtendende.setText("Atendente:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jLNumChamado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNumChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAtendende)
                    .addComponent(jLData)
                    .addComponent(jLClassificacao)
                    .addComponent(jLNomeCliente)
                    .addComponent(jLCpfCnpj)
                    .addComponent(jLNomeFantasia)
                    .addComponent(jLContato)
                    .addComponent(jLReclamante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTNomeCliente)
                        .addComponent(jTCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                        .addComponent(jTReclamante, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                        .addComponent(jTContato))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFData, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCClassificacao, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE))
                    .addComponent(jTAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuscarCliente)
                    .addComponent(jLNumChamado)
                    .addComponent(jTNumChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCpfCnpj)
                    .addComponent(jTCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeCliente)
                    .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeFantasia)
                    .addComponent(jTNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContato)
                    .addComponent(jTContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLReclamante)
                    .addComponent(jTReclamante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLClassificacao)
                    .addComponent(jCClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLData)
                    .addComponent(jFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAtendende))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Dados do Cliente", jPanel4);

        jLProblemaRelatado.setText("Problema Relatado:");

        jSProblemaRelatado.setViewportView(jTProblemaRelatado);

        jLDadosAnalisados.setText("Dados Analisados:");

        jSDadosAnalisados.setViewportView(jTDadosAnalisados);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSDadosAnalisados, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLProblemaRelatado)
                        .addComponent(jLDadosAnalisados)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jSProblemaRelatado, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLProblemaRelatado)
                .addGap(18, 18, 18)
                .addComponent(jSProblemaRelatado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLDadosAnalisados)
                .addGap(18, 18, 18)
                .addComponent(jSDadosAnalisados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Dados do Chamado", jPanel6);

        jLPossivelSolucao.setText("Possivel Solução:");

        jSPossivelSolucao.setViewportView(jTPossivelSolucao);

        jLSolucaoAplicada.setText("Solução Aplicada:");

        jTSolucaoAplicada.setColumns(20);
        jTSolucaoAplicada.setRows(5);
        jSsolucaoAplicada.setViewportView(jTSolucaoAplicada);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSsolucaoAplicada, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jSPossivelSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLSolucaoAplicada)
                                .addComponent(jLPossivelSolucao)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLPossivelSolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSPossivelSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLSolucaoAplicada)
                .addGap(18, 18, 18)
                .addComponent(jSsolucaoAplicada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Solução do Problema", jPanel8);

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/forbidden.png"))); // NOI18N
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/check.png"))); // NOI18N
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCancelar)
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarClienteActionPerformed
        Clientes client = new Clientes();
        client.setVisible(true);
        Clientes cliente = clTableModel.getValue(jTCliente.getSelectedRow());
    }//GEN-LAST:event_jBBuscarClienteActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        try {
            salvar();
        } catch (ParseException ex) {
            Logger.getLogger(CadastroChamados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jCClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCClassificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCClassificacaoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCliente;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCClassificacao;
    private javax.swing.JFormattedTextField jFData;
    private javax.swing.JLabel jLAtendende;
    private javax.swing.JLabel jLClassificacao;
    private javax.swing.JLabel jLContato;
    private javax.swing.JLabel jLCpfCnpj;
    private javax.swing.JLabel jLDadosAnalisados;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLNomeCliente;
    private javax.swing.JLabel jLNomeFantasia;
    private javax.swing.JLabel jLNumChamado;
    private javax.swing.JLabel jLPossivelSolucao;
    private javax.swing.JLabel jLProblemaRelatado;
    private javax.swing.JLabel jLReclamante;
    private javax.swing.JLabel jLSolucaoAplicada;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jSDadosAnalisados;
    private javax.swing.JScrollPane jSPossivelSolucao;
    private javax.swing.JScrollPane jSProblemaRelatado;
    private javax.swing.JScrollPane jSsolucaoAplicada;
    private javax.swing.JTextField jTAtendente;
    private javax.swing.JTextField jTContato;
    private javax.swing.JTextField jTCpfCnpj;
    private javax.swing.JTextPane jTDadosAnalisados;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JTextField jTNomeFantasia;
    private javax.swing.JTextField jTNumChamado;
    private javax.swing.JTextPane jTPossivelSolucao;
    private javax.swing.JTextPane jTProblemaRelatado;
    private javax.swing.JTextField jTReclamante;
    private javax.swing.JTextArea jTSolucaoAplicada;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
    private void salvar() throws ParseException {
        Cliente cliente = new Cliente();
        cliente.setCpf(jTCpfCnpj.getText());
        cliente.setNome(jTNomeCliente.getText());
        cliente.setFantasia(jTNomeFantasia.getText());
        Telefone telefone = new Telefone();
        telefone.setTelefone1(jTContato.getText());
        cliente.setTelefone(telefone);
        Date data = DateFormat.getInstance().parse(jLData.getText());
        br.com.rtsistema.domain.Chamados chamados = new br.com.rtsistema.domain.Chamados();
        chamados.setReclamante(jTReclamante.getText());
        chamados.setData(data);
        chamados.setProblemaRelatado(jTProblemaRelatado.getText());
        chamados.setDadosAnalisado(jTDadosAnalisados.getText());
        chamados.setPossivelSolucao(jTPossivelSolucao.getText());
        chamados.setSolucaoAplicada(jTSolucaoAplicada.getText());
        CadastroChamadosDao cdChamadoDao = new CadastroChamadosDao();
        cdChamadoDao.salvar(chamados);
        JOptionPane.showMessageDialog(null, "Operação Salva com sucesso!");
        jTCpfCnpj.setText("");
        jTNomeCliente.setText("");

    }

}
