/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rtsistema.views;

import br.com.rtisistemas.tableModel.ClientesTableModel;
import br.com.rtsistema.domain.Cliente;
import br.com.rtsistema.persistence.CadastroClienteDao;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Helton
 */
public class Clientes extends javax.swing.JDialog {

    ClientesTableModel clTableModel = new ClientesTableModel();
    private List<Cliente> clientes;

    public Clientes() {
        initComponents();
        CadastroClienteDao cdClienteDao = new CadastroClienteDao();
        clientes = cdClienteDao.findAll();
        clTableModel.setLista(clientes);
        jTCliente.setModel(clTableModel);
        setModal(true);
    }

    public Clientes(Boolean exibirBotao) {
        this();
        jBselecionarCliente.setVisible(exibirBotao);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jBselecionarCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMnovo = new javax.swing.JMenuItem();
        jMAlterar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCliente);

        jBselecionarCliente.setText("Selecionar Cliente");
        jBselecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarClienteActionPerformed(evt);
            }
        });

        jMArquivo.setText("Arquivo");

        jMnovo.setText("Novo");
        jMnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnovoActionPerformed(evt);
            }
        });
        jMArquivo.add(jMnovo);

        jMAlterar.setText("Alterar");
        jMAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlterarActionPerformed(evt);
            }
        });
        jMArquivo.add(jMAlterar);

        jMenuBar1.add(jMArquivo);

        jMenu2.setText("Localizar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBselecionarCliente)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBselecionarCliente)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnovoActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_jMnovoActionPerformed

    private void jMAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlterarActionPerformed
        Cliente cliente = clTableModel.getValue(jTCliente.getSelectedRow());
        CadastroCliente cadastroCliente = new CadastroCliente(cliente);

    }//GEN-LAST:event_jMAlterarActionPerformed

    private void jBselecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarClienteActionPerformed
        Cliente client = clTableModel.getValue(jTCliente.getSelectedRow());
        CadastroChamados cdChamados = new CadastroChamados(client);
        cdChamados.setVisible(true);
    }//GEN-LAST:event_jBselecionarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBselecionarCliente;
    private javax.swing.JMenuItem jMAlterar;
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCliente;
    // End of variables declaration//GEN-END:variables

}
